#!/usr/bin/python

import sys
from django.core.management import setup_environ

import settings

if __name__ == "__main__":
    setup_environ(settings)

    from spammer.spammer import SpammerMain
    SpammerMain.initialize()

